version: '3.8'

services:
  codegen-agent:
    build:
      context: ./codegen-agent
      dockerfile: Dockerfile
    env_file: ./codegen-agent/.env
    ports:
      - "8081:8081"  # Adjust the ports as necessary

  sast-agent:
    build:
      context: ./sast-agent
      dockerfile: Dockerfile
    ports:
      - "8082:8082"  # Adjust the ports as necessary

  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    ports:
      - "8083:8083"  # Adjust the ports as necessary
    depends_on:
      - codegen-agent
      - sast-agent
